//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 11:03:15 AM EDT 
//


package com.silverpop.api.client.command.elements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BehaviorElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BehaviorElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OPTION_OPERATOR" type="{SilverpopApi:EngageService.ListMgmt.UserActions}OptionOperator"/>
 *         &lt;element name="TYPE_OPERATOR" type="{SilverpopApi:EngageService.ListMgmt.UserActions}TypeOperator"/>
 *         &lt;element name="MAILING_ID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="REPORT_ID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="LINK_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WHERE_OPERATOR" type="{SilverpopApi:EngageService.ListMgmt.UserActions}WhereOperator" minOccurs="0"/>
 *         &lt;element name="CRITERIA_OPERATOR" type="{SilverpopApi:EngageService.ListMgmt.UserActions}CriteriaOperator" minOccurs="0"/>
 *         &lt;element name="VALUES" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BehaviorElementType", propOrder = {
    "optionoperator",
    "typeoperator",
    "mailingid",
    "reportid",
    "linkname",
    "whereoperator",
    "criteriaoperator",
    "values"
})
public class BehaviorElementType {

    @XmlElement(name = "OPTION_OPERATOR")
    protected int optionoperator;
    @XmlElement(name = "TYPE_OPERATOR")
    protected int typeoperator;
    @XmlElement(name = "MAILING_ID")
    protected Long mailingid;
    @XmlElement(name = "REPORT_ID")
    protected Long reportid;
    @XmlElement(name = "LINK_NAME")
    protected String linkname;
    @XmlElement(name = "WHERE_OPERATOR")
    protected Integer whereoperator;
    @XmlElement(name = "CRITERIA_OPERATOR")
    protected String criteriaoperator;
    @XmlElement(name = "VALUES")
    protected String values;

    /**
     * Gets the value of the optionoperator property.
     * 
     */
    public int getOPTIONOPERATOR() {
        return optionoperator;
    }

    /**
     * Sets the value of the optionoperator property.
     * 
     */
    public void setOPTIONOPERATOR(int value) {
        this.optionoperator = value;
    }

    /**
     * Gets the value of the typeoperator property.
     * 
     */
    public int getTYPEOPERATOR() {
        return typeoperator;
    }

    /**
     * Sets the value of the typeoperator property.
     * 
     */
    public void setTYPEOPERATOR(int value) {
        this.typeoperator = value;
    }

    /**
     * Gets the value of the mailingid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMAILINGID() {
        return mailingid;
    }

    /**
     * Sets the value of the mailingid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMAILINGID(Long value) {
        this.mailingid = value;
    }

    /**
     * Gets the value of the reportid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getREPORTID() {
        return reportid;
    }

    /**
     * Sets the value of the reportid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setREPORTID(Long value) {
        this.reportid = value;
    }

    /**
     * Gets the value of the linkname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINKNAME() {
        return linkname;
    }

    /**
     * Sets the value of the linkname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINKNAME(String value) {
        this.linkname = value;
    }

    /**
     * Gets the value of the whereoperator property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWHEREOPERATOR() {
        return whereoperator;
    }

    /**
     * Sets the value of the whereoperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWHEREOPERATOR(Integer value) {
        this.whereoperator = value;
    }

    /**
     * Gets the value of the criteriaoperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRITERIAOPERATOR() {
        return criteriaoperator;
    }

    /**
     * Sets the value of the criteriaoperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRITERIAOPERATOR(String value) {
        this.criteriaoperator = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALUES() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALUES(String value) {
        this.values = value;
    }

}
