//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 11:03:15 AM EDT 
//


package com.silverpop.api.client.command.elements;

import com.thoughtworks.xstream.annotations.XStreamAlias;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RulesetElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RulesetElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RULESET_ID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="LIST_ID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="RULESET_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CONTENT_AREAS" type="{SilverpopApi:EngageService.MailManagement.UserActions}ContentAreasElementType"/>
 *         &lt;element name="RULES" type="{SilverpopApi:EngageService.MailManagement.UserActions}RulesElementType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XStreamAlias("RULESET")
public class RulesetElementType {

    @XStreamAlias("RULESET_ID")
    protected Long rulesetid;
    @XStreamAlias("LIST_ID")
    protected Long listid;
    @XStreamAlias("RULESET_NAME")
    protected String rulesetname;
    @XStreamAlias("CONTENT_AREAS")
    protected ContentAreasElementType contentareas;
    @XStreamAlias("RULES")
    protected RulesElementType rules;

    /**
     * Gets the value of the rulesetid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRULESETID() {
        return rulesetid;
    }

    /**
     * Sets the value of the rulesetid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRULESETID(Long value) {
        this.rulesetid = value;
    }

    /**
     * Gets the value of the listid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLISTID() {
        return listid;
    }

    /**
     * Sets the value of the listid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLISTID(Long value) {
        this.listid = value;
    }

    /**
     * Gets the value of the rulesetname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRULESETNAME() {
        return rulesetname;
    }

    /**
     * Sets the value of the rulesetname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRULESETNAME(String value) {
        this.rulesetname = value;
    }

    /**
     * Gets the value of the contentareas property.
     * 
     * @return
     *     possible object is
     *     {@link ContentAreasElementType }
     *     
     */
    public ContentAreasElementType getCONTENTAREAS() {
        return contentareas;
    }

    /**
     * Sets the value of the contentareas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentAreasElementType }
     *     
     */
    public void setCONTENTAREAS(ContentAreasElementType value) {
        this.contentareas = value;
    }

    /**
     * Gets the value of the rules property.
     * 
     * @return
     *     possible object is
     *     {@link RulesElementType }
     *     
     */
    public RulesElementType getRULES() {
        return rules;
    }

    /**
     * Sets the value of the rules property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesElementType }
     *     
     */
    public void setRULES(RulesElementType value) {
        this.rules = value;
    }

}
