//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 11:03:15 AM EDT 
//


package com.silverpop.api.client.command.elements;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SendTimeOptimization.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SendTimeOptimization">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="SEND_24HRS"/>
 *     &lt;enumeration value="SEND_WEEK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "SendTimeOptimization")
@XmlEnum
public enum SendTimeOptimization {

    NONE("NONE"),
    @XmlEnumValue("SEND_24HRS")
    SEND_24_HRS("SEND_24HRS"),
    SEND_WEEK("SEND_WEEK");
    private final String value;

    SendTimeOptimization(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SendTimeOptimization fromValue(String v) {
        for (SendTimeOptimization c: SendTimeOptimization.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
