//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 11:03:15 AM EDT 
//


package com.silverpop.api.client.command.elements;

import com.thoughtworks.xstream.annotations.XStreamAlias;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TableElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TABLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TABLE_COLUMNS" type="{SilverpopApi:EngageService.ListMgmt.RecipientActions}TableColumnsElementType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XStreamAlias("TABLE")
public class TableElementType {

    @XStreamAlias("TABLE_NAME")
    protected String tablename;
    @XStreamAlias("TABLE_COLUMNS")
    protected TableColumnsElementType tablecolumns;

    /**
     * Gets the value of the tablename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTABLENAME() {
        return tablename;
    }

    /**
     * Sets the value of the tablename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTABLENAME(String value) {
        this.tablename = value;
    }

    /**
     * Gets the value of the tablecolumns property.
     * 
     * @return
     *     possible object is
     *     {@link TableColumnsElementType }
     *     
     */
    public TableColumnsElementType getTABLECOLUMNS() {
        return tablecolumns;
    }

    /**
     * Sets the value of the tablecolumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableColumnsElementType }
     *     
     */
    public void setTABLECOLUMNS(TableColumnsElementType value) {
        this.tablecolumns = value;
    }

}
