//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 11:03:15 AM EDT 
//


package com.silverpop.api.client.command.elements;

import com.thoughtworks.xstream.annotations.XStreamAlias;


/**
 * <p>Java class for TableColumnElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableColumnElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TYPE" type="{SilverpopApi:EngageService.ListMgmt.UserActions}TableColumnType"/>
 *         &lt;element name="IS_REQUIRED" type="{SilverpopApi:EngageService.ListMgmt.UserActions}True" minOccurs="0"/>
 *         &lt;element name="KEY_COLUMN" type="{SilverpopApi:EngageService.ListMgmt.UserActions}True" minOccurs="0"/>
 *         &lt;element name="DEFAULT_VALUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SELECTION_VALUES" type="{SilverpopApi:EngageService.ListMgmt.UserActions}SelectionValuesElementType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XStreamAlias("COLUMN")
public class TableColumnElementType {

    @XStreamAlias("NAME")
    protected String name;
    @XStreamAlias("TYPE")
    protected String type;
    @XStreamAlias("VALUE")
    protected String value;
    @XStreamAlias("IS_REQUIRED")
    protected Boolean isrequired;
    @XStreamAlias("KEY_COLUMN")
    protected Boolean keycolumn;
    @XStreamAlias("DEFAULT_VALUE")
    protected String defaultvalue;
    @XStreamAlias("SELECTION_VALUES")
    protected SelectionValuesElementType selectionvalues;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTYPE(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the isrequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isISREQUIRED() {
        return isrequired;
    }

    /**
     * Sets the value of the isrequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setISREQUIRED(Boolean value) {
        this.isrequired = value;
    }

    /**
     * Gets the value of the keycolumn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKEYCOLUMN() {
        return keycolumn;
    }

    /**
     * Sets the value of the keycolumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKEYCOLUMN(Boolean value) {
        this.keycolumn = value;
    }

    /**
     * Gets the value of the defaultvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEFAULTVALUE() {
        return defaultvalue;
    }

    /**
     * Sets the value of the defaultvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEFAULTVALUE(String value) {
        this.defaultvalue = value;
    }

    /**
     * Gets the value of the selectionvalues property.
     * 
     * @return
     *     possible object is
     *     {@link SelectionValuesElementType }
     *     
     */
    public SelectionValuesElementType getSELECTIONVALUES() {
        return selectionvalues;
    }

    /**
     * Sets the value of the selectionvalues property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectionValuesElementType }
     *     
     */
    public void setSELECTIONVALUES(SelectionValuesElementType value) {
        this.selectionvalues = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
