//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 11:03:15 AM EDT 
//


package com.silverpop.api.client.command.elements;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TableColumnType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TableColumnType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TEXT"/>
 *     &lt;enumeration value="YESNO"/>
 *     &lt;enumeration value="NUMERIC"/>
 *     &lt;enumeration value="DATE"/>
 *     &lt;enumeration value="TIME"/>
 *     &lt;enumeration value="COUNTRY"/>
 *     &lt;enumeration value="SELECTION"/>
 *     &lt;enumeration value="EMAIL"/>
 *     &lt;enumeration value="DATE_TIME"/>
 *     &lt;enumeration value="SYNC_ID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TableColumnType")
@XmlEnum
public enum TableColumnType {

    TEXT,
    YESNO,
    NUMERIC,
    DATE,
    TIME,
    COUNTRY,
    SELECTION,
    EMAIL,
    DATE_TIME,
    SYNC_ID;

    public String value() {
        return name();
    }

    public static TableColumnType fromValue(String v) {
        return valueOf(v);
    }

}
