//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 11:03:15 AM EDT 
//


package com.silverpop.api.client.command.elements;

import com.silverpop.api.client.XmlApiProperties;
import com.thoughtworks.xstream.annotations.XStreamAlias;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrackingMetricMailingElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrackingMetricMailingElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JOB_ID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="MAILING_ID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="FILE_PATH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SENT_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlApiProperties("MAILING")
public class TrackingMetricMailingElementType {

    @XStreamAlias("JOB_ID")
    protected Long jobid;
    @XStreamAlias("MAILING_ID")
    protected Long mailingid;
    @XStreamAlias("FILE_PATH")
    protected String filepath;
    @XStreamAlias("SENT_DATE")
    protected String sentdate;

    /**
     * Gets the value of the jobid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getJOBID() {
        return jobid;
    }

    /**
     * Sets the value of the jobid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setJOBID(Long value) {
        this.jobid = value;
    }

    /**
     * Gets the value of the mailingid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMAILINGID() {
        return mailingid;
    }

    /**
     * Sets the value of the mailingid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMAILINGID(Long value) {
        this.mailingid = value;
    }

    /**
     * Gets the value of the filepath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFILEPATH() {
        return filepath;
    }

    /**
     * Sets the value of the filepath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFILEPATH(String value) {
        this.filepath = value;
    }

    /**
     * Gets the value of the sentdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSENTDATE() {
        return sentdate;
    }

    /**
     * Sets the value of the sentdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSENTDATE(String value) {
        this.sentdate = value;
    }

}
